version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html:delegated

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./:/var/www/html

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]